name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.13'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # conda env update --file requirements.txt --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install pytest
      run: |
        conda install pytest
    # Bypassing pytest step
    # - name: Test with pytest
    #   run: |
    #     pytest
    - name: Install Jupyter Notebook
      run: |
          python -m pip install jupyter
    - name: Execute Jupyter Notebook
      run: jupyter execute jobs_analysis_test.ipynb
      shell: bash
